#!/usr/bin/env bash
# configure ngix server so that '/redirect_me' redirects to another page

# Install Nginx if not installed
if ! dpkg -l | grep -q nginx; then
   sudo apt-get update
   sudo apt-get install -y nginx
fi

sudo service nginx start

# Define the redirection configuration
new_redirection="server_name _;\\n\\trewrite ^/redirect https://twitter.com/AfricaFactsZone/status/1698342840177168463 permanent;"

# Enable the redirection in Nginx configuration
sudo sed -i "s#server_name _;#$new_redirection#" /etc/nginx/sites-available/default

# test configuration and reload
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
