#!/usr/bin/env bash
# configure ngix server so that '/redirect_me' redirects to another page

# Install Nginx if not installed
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Pontuagi permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# restarn Nginx
sudo service nginx restart
