#!/bin/bash
# configure ngix server so that '/redirect_me' redirects to another page

# Install Nginx if not installed
sudo apt-get update
sudo apt-get install -y nginx

# Nginx configuration for redirection
echo "
server {
	listen 80 default_server;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee /etc/nginx/sites-available/redirect.conf

# Symbolic to enable new configuration
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# test configuration and reload
sudo nginx -t
sudo service nginx reload
