#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update the system
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# Create a new HAProxy configuration file
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    maxconn 4096
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    maxconn 2000
    timeout connect 5s
    timeout client 30s
    timeout server 30s

frontend http-in
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 100.26.136.11:80 check
    server web-02 54.236.190.242:80 check
EOF


# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Start HAProxy
sudo service haproxy start

# Check HAProxy status
sudo service haproxy status

echo "HAProxy is now configured and running." 
