#!/usr/bin/env bash
# A script that displays the content of the file '/etc/passwd

while IFS=: read -r username _ userid _ _ home _; do
	echo "$username"
	echo "$userid"
	echo "$home"
done < /etc/passwd
