#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username groupid userid homedirectory commandshell password useridinfo; do
	echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $commandshell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
