#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code, and displays this data.

cat apache-access.log | awk '{ count[$1 " " $9]++ } END { for (key in count) printf "     %d %s\n", count[key], key }' | sort -nr
