#!/usr/bin/env bash
#a script that loops from 1 to 10 and displays:
# - 'bad luck' in the 4th iteration
# - 'good luck' in the 8 iteration 
# - and 'Best School' for the rest

i=0
while ((i<10)); do
	if ((i == 3)); then
		echo 'bad luck'
	elif ((i == 7)); then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	((i++))
done
