#!/usr/bin/env bash
# Loops from 1 to 20 displaying the numbers alongside;
# - 'bad luck from china' in the 4th loop
# - 'bad luck from japan' in the 9th loop
# - 'bad luck for Italy' in the 17th loop

i=1

while ((i<21)); do
	echo "$i"
	case $i in
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
			;;
	esac
	((i++))
done
