#!/usr/bin/env bash
# A script to run container as the nginx user.

# Step 1: Set read-only permissions for the Nginx configuration file
sudo chmod 400 /etc/nginx/nginx.conf

# Step 2: Change ownership of the Nginx configuration file to user and group 'nginx'
sudo chown nginx:nginx /etc/nginx/nginx.conf

# Step 3: Modify the Nginx site configuration to use port 8080 instead of 80
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Step 4: Terminate any running Apache processes
pkill apache

# Step 5: Restart the Nginx web server
sudo -u nginx service nginx restart
