#!/usr/bin/env bash
# Shorter version of 1-run_nginx_as_nginx
if [ "$(ps aux | grep nginx | grep -c root)" -gt 0 ]; then
    sudo systemctl stop nginx
    sudo sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf
    sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
    sudo systemctl start nginx
fi
