#!/usr/bin/env bash
# Shorter version of 1-run_nginx_as_nginx
sudo chmod 400 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache
sudo -u nginx service nginx restart
